### ISSUE TITLE
Possible to run on Linux using only free software?

### ISSUE THREAD

**Issue by petterreinholdtsen** [thewhobox/Kaenx#6]
Hi.  Is there any chance to get this system working on Linux using only free software?

Sorry for using English, but my german is very lousy. :)

**Comment by thewhobox** [comment]
Hey,

it`s not possible to run the application on linux yet.
We will recode the application with the UNO-Platform after the configuration of KNX devices works good.

You're welcome :)

**Comment by petterreinholdtsen** [comment]
[Mike]
> it`s not possible to run the application on linux yet.
> We will recode the application with the UNO-Platform after the
> configuration of KNX devices works good.
>
> You're welcome :)

Sad to hear that running it under Wine do not work.  Perhaps something
to aim for in the short term, instead of delaying availability for Linux
users until the code is completely rewritten.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Mike]
> It's an UWP App. 
> There is no possibility to run it with wine or something else.

Aha.

I found some kind of recipe on 
<URL: https://askubuntu.com/questions/991858/is-it-possible-to-run-windows-10-uwp-apps-on-ubuntu/1300897 >,
and using unzip I was able to get access to a .exe file, but sadly
running it crashes like this:

  % wine Kaenx.exe 
  0009:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc79db4
  %

I hope you manage to get to a point where it can build and run natively
on Linux using only free software.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by thewhobox** [comment]
Hello,

this method wont fit for all uwp apps. Every App has different dependencies which have to be supported by wine.
In my App i also use Application Insights and AppCenter. Maybe these two causes the problem.

Bus since this isnt any official way i wont support it.
As i mentioned it before i will recode the app so it wil be crossplattform and run nativly on linux with Skia.
