### ISSUE TITLE
Provide some English description?

### ISSUE THREAD

**Issue by petterreinholdtsen** [thewhobox/Kaenx#7]
Hi.  I was recommeneded to check out Kaenx as a alternative to the ETS Windows software, as an free software alternative to program KNX devices without the terms of use of Microsoft and the KNX Association.  But it is hard to figure out what the program is all about, as I do not understand German very well.  Is there any hope to provide package description and instructions in English or Norwegian instead?

**Comment by thewhobox** [comment]
Hey,
i extended the readme and added an [english version](https://github.com/thewhobox/Kaenx/blob/master/README_en.md).
