### ISSUE TITLE
Herausgeberzertifikat abgelaufen

### ISSUE THREAD

**Issue by StefanJerek** [thewhobox/Kaenx#8]
@thewhobox: Das unter https://kaenx.mikegerst.de/Updater/Kaenx_0.0.55.0_Test/Kaenx_0.0.55.0_x86_x64.cer verlinkte Zertifikat ist am 07.08.22 abgelaufen. Das Zertifikat sollte erneuert werden.

**Comment by thewhobox** [comment]
Aufgrund der kommenden Neuentwicklung wird die vorkompilierte Version nicht mehr unterstützt.
Die Anwendung kann jedoch auch leicht selbst mit Visual Studio erstellt werden.
